# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Wordrobe Books
email: wordrobebooks@velichamtech.com
  #Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
  Digital library for Islamic books in Malayalam
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://WordrobeBooks.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Velicham Tech Inc.
address_line: 268 McNaughton Ave W, Chatham, ON, N7L 1R7, Canada
telephone_number: 1 519 953 5818
fax_number: 1 519 953 5818
company_email: support@wordrobebooks.com
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d558.9946668432133!2d-82.20847863202658!3d42.40871603208767!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x882ff9ba56f9a087%3A0xaa01375b67ce61a6!2s268%20McNaughton%20Ave%20W%2C%20Chatham%2C%20ON%20N7L%201R8!5e0!3m2!1sen!2sca!4v1678590038361!5m2!1sen!2sca

# Social Link
  #twitter_username: wordrobeBooks
  #github_username:  jekyll
facebook_link: http://www.facebook.com/people/Wordrobe-Books/100086653119013/
twitter_link: http://www.twitter.com/wordrobebooks
instagram_link: https://www.instagram.com/wordrobebooks
# linkedin_link: http://www.linkedin.com
# googleplus_link: http://plus.google.com

# Build settings
  #theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

# include .well-known folder
include: [".well-known"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
